<a href="https://colab.research.google.com/github/finnjaby/CampusDataProject/blob/main/CampusDataProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Campus Environmental Dataset Project
Finnja Bayer, 2026

## Data Preparation
This section loads the data set and prepares it for analysis

In [1]:
import pandas as pd

### Load the Dataset

In [2]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Project/CampusWalkDataset_061026FB.csv', skiprows = 4)

Inspect dataset structure...

In [3]:
print("Column names:")
print(df.dtypes)

print("\nSample Rows\n")
print(df.head())

Column names:
recorder_id                               object
date                                      object
location                                  object
weather                                   object
temperature_c                             object
sound level                               object
foot_traffic                              object
primary_sound_type_urban                  object
other_sound_type_urban                    object
primary_sound_type_nature                 object
other_sound_type_nature                   object
insects_count                            float64
birds_count                              float64
trees_presence                            object
native_or_wild_plant_presence             object
ornnamental_or_planted_plant_presence     object
moss_or_lichen_presence                   object
wellbeing_rating                          object
ease_rating                               object
stress_rating                             object
nature_connection_experience_rating       object
most_notable_nature_element               object
other_notes                               object
Unnamed: 23                              float64
Unnamed: 24                              float64
Unnamed: 25                              float64
Unnamed: 26                              float64
dtype: object

Sample Rows

  recorder_id        date                        location        weather  \
0     R26_001  22/09/2026                L01 MainEntrance  Partly cloudy
1     R26_001  22/09/2026                L02 LibraryGreen          Sunny
2     R26_001  22/09/2026   L06 HedgingBehindSportsCentre  Partly cloudy
3     R26_001  22/09/2026  L08 AccessRoadNearSportsCentre  Partly cloudy
4     R26_001  22/09/2026   L06 HedgingBehindSportsCentre          Sunny

  temperature_c sound level foot_traffic primary_sound_type_urban  \
0            16       Quiet          Low             Human voices
1            16    Moderate          Low                  Traffic
2            16       Quiet          Low             Construction
3            16    Moderate          Low             Human voices
4            16    Moderate          Low                  Traffic

  other_sound_type_urban primary_sound_type_nature  ...    wellbeing_rating  \
0                Traffic                      Wind  ...  Positive wellbeing
1           Human voices                      Wind  ...  Positive wellbeing
2                Traffic                      Wind  ...  Positive wellbeing
3           Human voices                      Wind  ...  Positive wellbeing
4                  Other                      Wind  ...  Positive wellbeing

   ease_rating  stress_rating nature_connection_experience_rating  \
0      Neutral      Stressful                      Less connected
1      Neutral        Neutral             A little more connected
2         Easy    Mostly calm                           No change
3      Neutral        Neutral                 Much more connected
4         Easy    Mostly calm                      Less connected

  most_notable_nature_element other_notes Unnamed: 23 Unnamed: 24 Unnamed: 25  \
0            Plants and trees         NaN         NaN         NaN         NaN
1            Sunrays on grass         NaN         NaN         NaN         NaN
2                  Very quiet         NaN         NaN         NaN         NaN
3                 Harsh wind          NaN         NaN         NaN         NaN
4               Crowded area          NaN         NaN         NaN         NaN

  Unnamed: 26
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN

[5 rows x 27 columns]

Exchanged with peers to make data more readable:

In [4]:
display(df.head(134))

,recorder_id,date,location,weather,temperature_c,sound level,foot_traffic,primary_sound_type_urban,other_sound_type_urban,primary_sound_type_nature,...,wellbeing_rating,ease_rating,stress_rating,nature_connection_experience_rating,most_notable_nature_element,other_notes,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
0,R26_001,22/09/2026,L01 MainEntrance,Partly cloudy,16,Quiet,Low,Human voices,Traffic,Wind,...,Positive wellbeing,Neutral,Stressful,Less connected,Plants and trees,NaN,NaN,NaN,NaN,NaN
1,R26_001,22/09/2026,L02 LibraryGreen,Sunny,16,Moderate,Low,Traffic,Human voices,Wind,...,Positive wellbeing,Neutral,Neutral,A little more connected,Sunrays on grass,NaN,NaN,NaN,NaN,NaN
2,R26_001,22/09/2026,L06 HedgingBehindSportsCentre,Partly cloudy,16,Quiet,Low,Construction,Traffic,Wind,...,Positive wellbeing,Easy,Mostly calm,No change,Very quiet,NaN,NaN,NaN,NaN,NaN
3,R26_001,22/09/2026,L08 AccessRoadNearSportsCentre,Partly cloudy,16,Moderate,Low,Human voices,Human voices,Wind,...,Positive wellbeing,Neutral,Neutral,Much more connected,Harsh wind,NaN,NaN,NaN,NaN,NaN
4,R26_001,22/09/2026,L06 HedgingBehindSportsCentre,Sunny,16,Moderate,Low,Traffic,Other,Wind,...,Positive wellbeing,Easy,Mostly calm,Less connected,Crowded area,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,R26_027,23/09/2026,L01 MainEntrance,Partly cloudy,17C,Moderate,High,Traffic,Human voices,Trees,...,Positive wellbeing,Neutral,Mostly calm,A little more connected,Grass,An insect was on my paper,NaN,NaN,NaN,NaN
130,R26_027,23/09/2026,L07 CarParkNearSportsCentre,Sunny,19C,Moderate,Moderate,Traffic,Human voices,Trees,...,Neutral,Easy,Mostly calm,No change,Plants,The parking is very full,NaN,NaN,NaN,NaN
131,R26_027,23/09/2026,L06 HedgingBehindSportsCentre,Sunny,18C,Moderate,Moderate,Human voices,Traffic,Wind,...,Positive wellbeing,Easy,Mostly calm,A little more connected,Grass,Small apple tree,NaN,NaN,NaN,NaN
132,R26_027,23/09/2026,L05 GreenFrontSportsCentre,Windy,16C,Quiet,Low,Traffic,Human voices,Other birds,...,Low wellbeing,Slighly uneasy,Neutral,Less connected,Trees,There are clothes left near a tree,NaN,NaN,NaN,NaN
133,R26_027,23/09/2026,L04 PathFrontiHub,Windy,16C,Quiet,Low,Traffic,Human voices,Trees,...,Positive wellbeing,Easy,Mostly calm,Much more connected,Plants,NaN,NaN,NaN,NaN,NaN

### Cleaning data

#### Removing empty columns

Removing all empty columns at the end by name, while preventing errors when cell is rerun.

In [5]:
to_drop = ['Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26']
df.drop(to_drop, inplace=True, axis=1, errors = 'ignore')

display(df.head())

,recorder_id,date,location,weather,temperature_c,sound level,foot_traffic,primary_sound_type_urban,other_sound_type_urban,primary_sound_type_nature,...,trees_presence,native_or_wild_plant_presence,ornnamental_or_planted_plant_presence,moss_or_lichen_presence,wellbeing_rating,ease_rating,stress_rating,nature_connection_experience_rating,most_notable_nature_element,other_notes
0,R26_001,22/09/2026,L01 MainEntrance,Partly cloudy,16,Quiet,Low,Human voices,Traffic,Wind,...,Many,Some,Some,Some,Positive wellbeing,Neutral,Stressful,Less connected,Plants and trees,NaN
1,R26_001,22/09/2026,L02 LibraryGreen,Sunny,16,Moderate,Low,Traffic,Human voices,Wind,...,Many,NaN,Some,NaN,Positive wellbeing,Neutral,Neutral,A little more connected,Sunrays on grass,NaN
2,R26_001,22/09/2026,L06 HedgingBehindSportsCentre,Partly cloudy,16,Quiet,Low,Construction,Traffic,Wind,...,Many,NaN,Many,Some,Positive wellbeing,Easy,Mostly calm,No change,Very quiet,NaN
3,R26_001,22/09/2026,L08 AccessRoadNearSportsCentre,Partly cloudy,16,Moderate,Low,Human voices,Human voices,Wind,...,One or two,Some,NaN,Some,Positive wellbeing,Neutral,Neutral,Much more connected,Harsh wind,NaN
4,R26_001,22/09/2026,L06 HedgingBehindSportsCentre,Sunny,16,Moderate,Low,Traffic,Other,Wind,...,One or two,NaN,Some,NaN,Positive wellbeing,Easy,Mostly calm,Less connected,Crowded area,NaN

#### Correcting dates

Changed incorrect rec_id values manually

In [6]:
display(df.iloc[94:98,0])

94    R26_020
95    R26_021
96    R26_022
97    R26_023
Name: recorder_id, dtype: object

In [7]:
df.loc[94:98, 'recorder_id'] = 'R26_020'

In [8]:
display(df.iloc[94:98,0])

94    R26_020
95    R26_020
96    R26_020
97    R26_020
Name: recorder_id, dtype: object

Convert recorder ids to their numbers for simplification

In [11]:
df['recorder_id'] = pd.to_numeric(
    df['recorder_id'].astype(str).str.extract(r'(\d+)$')[0],
    errors='coerce'
).fillna(-1).astype(int).astype(str)

df['recorder_id'] = df['recorder_id'].replace('-1', 'Unknown')

display(df.head(134))

,recorder_id,date,location,weather,temperature_c,sound level,foot_traffic,primary_sound_type_urban,other_sound_type_urban,primary_sound_type_nature,...,trees_presence,native_or_wild_plant_presence,ornnamental_or_planted_plant_presence,moss_or_lichen_presence,wellbeing_rating,ease_rating,stress_rating,nature_connection_experience_rating,most_notable_nature_element,other_notes
0,1,22/09/2026,L01 MainEntrance,Partly cloudy,16,Quiet,Low,Human voices,Traffic,Wind,...,Many,Some,Some,Some,Positive wellbeing,Neutral,Stressful,Less connected,Plants and trees,NaN
1,1,22/09/2026,L02 LibraryGreen,Sunny,16,Moderate,Low,Traffic,Human voices,Wind,...,Many,NaN,Some,NaN,Positive wellbeing,Neutral,Neutral,A little more connected,Sunrays on grass,NaN
2,1,22/09/2026,L06 HedgingBehindSportsCentre,Partly cloudy,16,Quiet,Low,Construction,Traffic,Wind,...,Many,NaN,Many,Some,Positive wellbeing,Easy,Mostly calm,No change,Very quiet,NaN
3,1,22/09/2026,L08 AccessRoadNearSportsCentre,Partly cloudy,16,Moderate,Low,Human voices,Human voices,Wind,...,One or two,Some,NaN,Some,Positive wellbeing,Neutral,Neutral,Much more connected,Harsh wind,NaN
4,1,22/09/2026,L06 HedgingBehindSportsCentre,Sunny,16,Moderate,Low,Traffic,Other,Wind,...,One or two,NaN,Some,NaN,Positive wellbeing,Easy,Mostly calm,Less connected,Crowded area,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,27,23/09/2026,L01 MainEntrance,Partly cloudy,17C,Moderate,High,Traffic,Human voices,Trees,...,Many,Some,NaN,Many,Positive wellbeing,Neutral,Mostly calm,A little more connected,Grass,An insect was on my paper
130,27,23/09/2026,L07 CarParkNearSportsCentre,Sunny,19C,Moderate,Moderate,Traffic,Human voices,Trees,...,One or two,Many,NaN,NaN,Neutral,Easy,Mostly calm,No change,Plants,The parking is very full
131,27,23/09/2026,L06 HedgingBehindSportsCentre,Sunny,18C,Moderate,Moderate,Human voices,Traffic,Wind,...,One or two,Some,NaN,NaN,Positive wellbeing,Easy,Mostly calm,A little more connected,Grass,Small apple tree
132,27,23/09/2026,L05 GreenFrontSportsCentre,Windy,16C,Quiet,Low,Traffic,Human voices,Other birds,...,Many,Some,Some,Some,Low wellbeing,Slighly uneasy,Neutral,Less connected,Trees,There are clothes left near a tree
133,27,23/09/2026,L04 PathFrontiHub,Windy,16C,Quiet,Low,Traffic,Human voices,Trees,...,Many,Some,Some,NaN,Positive wellbeing,Easy,Mostly calm,Much more connected,Plants,NaN

Changing wrong dates by splitting ids into groups a and b and assigning dates for excursions